### ISSUE TITLE
webpack-hot-reload

### ISSUE THREAD

**Issue by madurmanov** [pofigizm/front-core#6]
Обновление работает только для страниц, уровень врапера не обновляется, верно?

**Comment by pofigizm** [comment]
Скорее всего да, но это из-за того что в моем кейсе враппер внутри нпм-пакета и его разрабатывать не нужно.

**Comment by madurmanov** [comment]
Значит, чтобы шаблон тоже обновлялся, нужно render(https://github.com/pofigizm/front-core/blob/master/src/root.js#L20) вынести в отдельный файл и из рута хотрелоад вешать на этот файл(https://github.com/pofigizm/front-core/blob/master/src/root.js#L53), да?
Если использовать front-core как пакет, то возможность переопределить шаблон отсутствует или в front-service-boilerplate src/components/_template и есть шаблон?

**Comment by pofigizm** [comment]
У меня была задача вынести общую часть.
Чтобы заработало нужно релодить по изменению Wrapper, также как для pages https://github.com/pofigizm/front-core/blob/master/src/root.js#L53

**Comment by madurmanov** [comment]
Окей, спасибо!
